Models/ViewModels/ManageUserRolesViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TheBugTracker.Models.ViewModels
{
    public class ManageUserRolesViewModel
    {
        public BTUser BTUser { get; set; }
        public MultiSelectList Roles { get; set; }
        public List<string>? SelectedRoles { get; set; }

    }
}

Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.Design;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using TheBugTracker.Data;
using TheBugTracker.Extensions;
using TheBugTracker.Models;
using TheBugTracker.Models.Enums;
using TheBugTracker.Models.ViewModels;
using TheBugTracker.Services;
using TheBugTracker.Services.Interfaces;

namespace TheBugTracker.Controllers
{
    [Authorize]
    public class TicketsController : Controller
    {
        #region Properties
        //private readonly ApplicationDbContext _context;
        private readonly UserManager<BTUser> _userManager;
        private readonly IBTProjectService _projectService;
        private readonly IBTLookupService _lookupService;
        private readonly IBTTicketService _ticketService;
        private readonly IBTFileService _fileService;
        private readonly IBTTicketHistoryService _ticketHistoryService;
        #endregion

        #region Constructor
        public TicketsController(ApplicationDbContext context, UserManager<BTUser> userManager,
            IBTLookupService lookupService, IBTTicketService ticketService, IBTProjectService projectService, IBTFileService fileService, IBTTicketHistoryService ticketHistoryService)
        {
           // _context = context;
            _userManager = userManager;
            _lookupService = lookupService;
            _ticketService = ticketService;
            _projectService = projectService;
            _fileService = fileService;
            _ticketHistoryService = ticketHistoryService;
        }
        #endregion

        #region  // GET: Tickets
        // GET: Tickets
        //public async Task<IActionResult> Index()
        //{
        //    var applicationDbContext = _context.Tickets.Include(t => t.DeveloperUser).Include(t => t.OwnerUser).Include(t => t.Project).Include(t => t.TicketPriority).Include(t => t.TicketStatus).Include(t => t.TicketType);
        //    return View(await applicationDbContext.ToListAsync());
        //}
        #endregion

        #region //GET: MyTickets
        //GET: MyTickets
        public async Task<IActionResult> MyTickets()
        {
            BTUser bTUser = new();
            List<Ticket> tickets = new();

            bTUser = await _userManager.GetUserAsync(User);
            tickets = await _ticketService.GetTicketsByUserIdAsync(bTUser.Id, bTUser.CompanyId);

            return View(tickets);
        }
        #endregion

        #region //GET: AllTickets
        //GET: AllTickets
        public async Task<IActionResult> AllTickets()
        {
            int companyId = User.Identity.GetCompanyId().Value;

            List<Ticket> tickets = await _ticketService.GetAllTicketsByCompanyAsync(companyId);

            if(  User.IsInRole(nameof(Roles.Developer)) || User.IsInRole(nameof(Roles.Submitter)))
            {
                return View(tickets.Where( t => t.Archived == false  )    );
            }
            else
            {
                return View(tickets);
            }
           
        }
        #endregion

        #region //GET: ArchivedTickets
        //GET: ArchivedTickets
        public async Task<IActionResult> ArchivedTickets()
        {
            int companyId = User.Identity.GetCompanyId().Value;

            List<Ticket> tickets = await _ticketService.GetArchivedTicketsAsync(companyId);

            return View(tickets);

        }
        #endregion

        #region //GET: UnassignedTickets
        [Authorize(Roles = "Admin, ProjectManager")]
        //GET: ArchivedTickets
        public async Task<IActionResult> UnassignedTickets()
        {
            int companyId = User.Identity.GetCompanyId().Value;
            string btUserId = _userManager.GetUserId(User);

            List<Ticket> tickets = await _ticketService.GetUnassignedTicketsAsync(companyId);

            if (User.IsInRole(nameof(Roles.Admin)))
            {
                return View(tickets);
            }
            else
            {
                // filter so PM can only view tickets for projects they are PM of
                List < Ticket > pmTickets = new();

                foreach (Ticket ticket in tickets)
                {
                    if (await _projectService.IsAssignedProjectManagerAsync(btUserId, ticket.ProjectId))
                    {
                        pmTickets.Add(ticket);
                    }
                }

                return View(pmTickets);
            }

        }
        #endregion

        #region //GET: AssignDeveloper
        //GET: AssignDeveloper
        [Authorize(Roles = "Admin, ProjectManager")]
        [HttpGet]

        public async Task<IActionResult> AssignDeveloper(int id)
        {

            AssignDeveloperViewModel model = new();

            model.Ticket = await _ticketService.GetTicketByIdAsync(id);
            model.Developers = new SelectList(await _projectService.GetProjectMembersByRoleAsync(model.Ticket.ProjectId, nameof(Roles.Developer)),
                                                "Id", "FullName");

            return View(model);
        }
        #endregion

        #region //POST: AssignDeveloper
        //POST: AssignDeveloper
        [Authorize(Roles = "Admin, ProjectManager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignDeveloper(AssignDeveloperViewModel model)
        {

            // Check for Demo User
            if (await IsDemoUser())
            {
                return new RedirectResult("~/Identity/Account/AccessDenied");
            }


            if (model.DeveloperId != null)
            {
                BTUser btUser = await _userManager.GetUserAsync(User);
                Ticket oldTicket = await _ticketService.GetTicketAsNoTrackingAsync(model.Ticket.Id);

                try
                {
                    await _ticketService.AssignTicketAsync(model.Ticket.Id, model.DeveloperId);
                    
                }
                catch (Exception)
                {

                    throw;
                }

                // Ticket history
                Ticket newTicket = await _ticketService.GetTicketAsNoTrackingAsync(model.Ticket.Id);
                await _ticketHistoryService.AddHistoryAsync(oldTicket, newTicket, btUser.Id);

                return RedirectToAction(nameof(Details), new { id = model.Ticket.Id });

            }

            return RedirectToAction(nameof(AssignDeveloper), new { id = model.Ticket.Id });
        } 
        #endregion

        #region // GET: Tickets/Details/5
        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null )
            {
                return NotFound();
            }


            Ticket ticket =  await _ticketService.GetTicketByIdAsync(id.Value);


            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        } 
        #endregion

        #region // GET: Tickets/Create
        // GET: Tickets/Create
        public async Task<IActionResult> Create()
        {
            BTUser btUser = await _userManager.GetUserAsync(User);

            int companyId = User.Identity.GetCompanyId().Value;

            if (User.IsInRole(nameof(Roles.Admin)))
            {
                ViewData["ProjectId"] = new SelectList(await _projectService.GetAllProjectsByCompanyAsync(companyId), "Id", "Name");
            }
            else
            {
                ViewData["ProjectId"] = new SelectList(await _projectService.GetUserProjectsAsync(btUser.Id), "Id", "Name");
            }

            ViewData["TicketPriorityId"] = new SelectList(await _lookupService.GetTicketPrioritiesAsync(), "Id", "Name");
            ViewData["TicketTypeId"] = new SelectList(await _lookupService.GetTicketTypesAsync(), "Id", "Name");

            return View();
        } 
        #endregion

        #region // POST: Tickets/Create
        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,ProjectId,TicketTypeId,TicketPriorityId")] Ticket ticket)
        {
            // Check for Demo User
            if (await IsDemoUser())
            {
                return new RedirectResult("~/Identity/Account/AccessDenied");
            }

            BTUser btUser = await _userManager.GetUserAsync(User);

            if (ModelState.IsValid)
            {
                try
                {
                    ticket.Created = DateTimeOffset.Now;
                    ticket.OwnerUserId = btUser.Id;

                    ticket.TicketStatusId = (await _ticketService.LookupTicketStatusIdAsync(nameof(BTTicketStatus.New))).Value;

                    await _ticketService.AddNewTicketAsync(ticket);


                    // Ticket history
                    Ticket newTicket = await _ticketService.GetTicketAsNoTrackingAsync(ticket.Id);
                    await _ticketHistoryService.AddHistoryAsync(null, newTicket, btUser.Id);


                }
                catch (Exception)
                {

                    throw;
                }


                return RedirectToAction(nameof(AllTickets));
            }

            // If model state not valid
            if (User.IsInRole(nameof(Roles.Admin)))
            {
                ViewData["ProjectId"] = new SelectList(await _projectService.GetAllProjectsByCompanyAsync(btUser.CompanyId), "Id", "Name");
            }

Controllers/UserRolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TheBugTracker.Extensions;
using TheBugTracker.Models;
using TheBugTracker.Models.Enums;
using TheBugTracker.Models.ViewModels;
using TheBugTracker.Services.Interfaces;

namespace TheBugTracker.Controllers
{
    [Authorize]
    public class UserRolesController : Controller
    {
        private readonly IBTRolesService _rolesService;
        private readonly IBTCompanyInfoService _companyInfoService;
        private readonly UserManager<BTUser> _userManager;

        public UserRolesController(IBTRolesService rolesService, 
                        IBTCompanyInfoService companyInfoService, 
                        UserManager<BTUser> userManager)
        {
            _rolesService = rolesService;
            _companyInfoService = companyInfoService;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> ManageUserRoles()
        {
            // Add instance of the ViewModel as a list
            List<ManageUserRolesViewModel> model = new();

            // Get CompanyId
            int companyId = User.Identity.GetCompanyId().Value;

            // Get all company users
            List<BTUser> users = await _companyInfoService.GetAllMembersAsync(companyId);

            foreach (BTUser user in users)
            {
                ManageUserRolesViewModel viewModel = new();

                viewModel.BTUser = user;

                // Get Roles for the user
                IEnumerable<string> selected = await _rolesService.GetUserRolesAsync(user);
               
                viewModel.Roles = new MultiSelectList(await _rolesService.GetRolesAsync(), "Name", "Name", selected);

                model.Add(viewModel);
            }


           // Return the model to the View
            return View(model);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageUserRoles(ManageUserRolesViewModel member)
        {

            // Check for Demo User
            if (await IsDemoUser())
            {
                return new RedirectResult("~/Identity/Account/AccessDenied");
            }

            // Get the company Id
            int companyId = User.Identity.GetCompanyId().Value;

            // Instantiate the BTUser
            BTUser user = (await _companyInfoService.GetAllMembersAsync(companyId)).FirstOrDefault(u => u.Id == member.BTUser.Id);

            // Get Roles for the user
            IEnumerable<string> roles = await _rolesService.GetUserRolesAsync(user);

            if (member.SelectedRoles != null)
            {
                // Remove user from their roles
                if (await _rolesService.RemoveUserFromRolesAsync(user, roles))
                {
                    // Add user to the new selected role(s)
                    foreach (string role in member.SelectedRoles)
                    {
                        await _rolesService.AddUserToRoleAsync(user, role);
                    }
                }
            }

            // Navigate back to the view
            return RedirectToAction(nameof(ManageUserRoles));
        }

        #region Is Demo User
        private async Task<bool> IsDemoUser()
        {
            // Check if Demo User
            BTUser btUser = await _userManager.GetUserAsync(User);
            if (await _userManager.IsInRoleAsync(btUser, nameof(Roles.DemoUser)))
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        #endregion
    }
}

Views/UserRoles/ManageUserRoles.cshtml
@model IEnumerable<TheBugTracker.Models.ViewModels.ManageUserRolesViewModel>



<div class="d-flex align-items-center">
    <a class="" asp-action="AllTickets" asp-controller="Tickets" 
    style="color: rgb(23, 123, 227); margin-right : 15px" >  <i class="fa fa-arrow-left fa-lg" aria-hidden="true"></i> </a>
    <h4 class="mb-0">Manage Member Roles</h4>
</div>

<div class="d-flex align-items-center" style="margin-bottom : 20px">
    <a class="" asp-action="Dashboard" asp-controller="Home" style="color: rgb(23, 123, 227); margin-right : 15px" >  <i class="fa fa-home fa-lg" aria-hidden="true"></i> </a>
    <p class="mb-0" style="margin-right : 5px">/ UserRoles</p>
    <p class="mb-0">/ ManageUserRoles</p>
</div>


<hr />



    <div class="row">
                                <!-- Column starts -->
                                <div class="col-xl-12">
                                    <div class="card dz-card" id="bootstrap-table1">
                                        <div class="card-header flex-wrap border-0">
                                            <div>
                                                <h4 class="card-title">Manage Member Roles</h4>

                                            </div>

                                        </div>
                                        <!--tab-content-->
                                        <div class="tab-content" id="myTabContent">
                                            <div class="tab-pane fade show active" id="Preview" role="tabpanel" aria-labelledby="home-tab">
                                                <div class="card-body pt-0">
                                                    <div class="table-responsive">
                                                        <table class="table table-responsive-md">
                                                            <thead>
                                                                <tr>
                                                                    <th style="width:80px;"><strong>First Name</strong></th>
                                                                    <th><strong>Last Name</strong></th>
                                                                    <th><strong>Email</strong></th>
                                                                    <th><strong>Role</strong></th>
                                                                  
                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                               

                                                              @foreach (var member in Model)
                                                          {   
                                                                    <tr>
                                                <td>
                                                @member.BTUser.FirstName
                                                </td>
                                                <td>
                                                @member.BTUser.LastName
                                                </td>
                                                <td>
                                                @member.BTUser.Email
                                                </td>
                                                <td>
                                                    <form asp-action="ManageUserRoles" asp-controller="UserRoles" method=post>
                                                        <input type="hidden" asp-for="@member.BTUser.Id" />
                                                        <div class="row">
                                                            <div class="col-6">
                                                                <div class="form-group">
                                                                    <select required asp-for="@member.SelectedRoles" class="form-control" asp-items="@member.Roles" multiple></select>
                                                                </div>
                                                            </div>
                                                            <div class="col-6 align-self-center">
                                                                <div class="form-group">
                                                                    <input type="submit" value="Assign Role(s)" class="btn btn-sm btn-info text-white" />
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </td>
                                            </tr>
                                                              }
                                                            </tbody>
                                                        </table>
                                                    </div>
                                                </div>

                                            </div>