Models/Project.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheBugTracker.Models
{
    public class Project
    {
        // Primary Key
        public int Id { get; set; }
       
        [Required]
        [StringLength(50)]
        [DisplayName("Project Name")]
        public string? Name { get; set; }

        [DisplayName("Description")]
        public string? Description { get; set; }

        [DisplayName("Start Date")]
        public DateTimeOffset StartDate { get; set; }

        [DisplayName("End Date")]
        public DateTimeOffset EndDate { get; set; }

        [DisplayName("Archived")]
        public bool Archived { get; set; }

        // Image
        [NotMapped]
        [DataType(DataType.Upload)]
        public IFormFile? ImageFormFile { get; set; }

        [DisplayName("File Name")]
        public string? ImageFileName { get; set; }
        public byte[]? ImageFileData { get; set; }

        [DisplayName("File Extension")]
        public string? ImageContentType { get; set; }

        // Foreign Keys
        [DisplayName("Company")]
        public int? CompanyId { get; set; }

        [DisplayName("Priority")]
        public int? ProjectPriorityId { get; set; }

        // -- Navigation Prop -- //

        public virtual Company Company { get; set; }
        public virtual ProjectPriority ProjectPriority { get; set; }

        public virtual ICollection<BTUser> Members { get; set; } = new HashSet<BTUser>();
        public virtual ICollection<Ticket> Tickets { get; set; } = new HashSet<Ticket>();



    }
}

Models/ViewModels/AssignPMViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TheBugTracker.Models.ViewModels
{
	public class AssignPMViewModel
	{
		public Project? Project { get; set; }
		public SelectList? PMList { get; set; }
		public string? PMId { get; set; }
	}
}

Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using TheBugTracker.Data;
using TheBugTracker.Extensions;
using TheBugTracker.Models;
using TheBugTracker.Models.Enums;
using TheBugTracker.Models.ViewModels;
using TheBugTracker.Services;
using TheBugTracker.Services.Interfaces;

namespace TheBugTracker.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<BTUser> _userManager;
        private readonly IBTLookupService _lookupService;
        private readonly IBTRolesService _rolesService;
        private readonly IBTProjectService _projectService;
        private readonly IBTFileService _fileService;
		private readonly IBTCompanyInfoService _companyInfoService;

		public ProjectsController(ApplicationDbContext context, UserManager<BTUser> userManager, IBTLookupService lookupService, IBTRolesService rolesService, IBTProjectService projectService, IBTFileService fileService, IBTCompanyInfoService companyInfoService)
		{
			_context = context;
			_userManager = userManager;
			_lookupService = lookupService;
			_rolesService = rolesService;
			_projectService = projectService;
			_fileService = fileService;
			_companyInfoService = companyInfoService;
		}

		#region // GET: Projects
		// GET: Projects
		public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Projects.Include(p => p.Company).Include(p => p.ProjectPriority);
            return View(await applicationDbContext.ToListAsync());
        }
        #endregion

        #region // GET: Projects/Details/5
        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null )
            {
                return NotFound();
            }

            int companyId = User.Identity.GetCompanyId().Value;

            Project project = await _projectService.GetProjectByIdAsync(id.Value, companyId) ;

            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }
        #endregion

        #region // GET: Projects/Create
        // GET: Projects/Create
        [Authorize(Roles = "Admin, ProjectManager")]
        public async Task<IActionResult> Create()
        {
            
            int companyId = User.Identity.GetCompanyId().Value;

            // Add ViewModel instance
            AddProjectWithPMViewModel model = new();

            // Load SelectLists with data, i.e. PMList & PriorityList
            model.PMList = new SelectList(await _rolesService.GetUsersInRoleAsync(Roles.ProjectManager.ToString(), companyId),
                         "Id", "FullName");
            model.PriorityList = new SelectList(await _lookupService.GetProjectPrioritiesAsync(), "Id", "Name");

            return View(model);
        }
        #endregion

        #region // POST: Projects/Create
        [Authorize(Roles = "Admin, ProjectManager")]
        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddProjectWithPMViewModel model)
        {

            // Check for Demo User
            if (await IsDemoUser())
            {
                return new RedirectResult("~/Identity/Account/AccessDenied");
            }

            if (model != null)
            {

                int companyId = User.Identity.GetCompanyId().Value;

                try
                {
                    // Add project image - NEED FIX
                    if (model.Project.ImageFormFile != null)
                    {
                        model.Project.ImageFileData = await _fileService.ConvertFileToByteArrayAsync(model.Project.ImageFormFile);
                        model.Project.ImageFileName = model.Project.ImageFormFile.FileName;
                        model.Project.ImageContentType = model.Project.ImageFormFile.ContentType;
                    }

                    // model.Project.Archived = false;
                    // Add companyId
                    model.Project.CompanyId = companyId;

                    await _projectService.AddNewProjectAsync(model.Project);

                    if (!String.IsNullOrEmpty(model.PmId))
                    {
                        await _projectService.AddProjectManagerAsync(model.PmId, model.Project.Id);
                    }

                    // TODO - Redirect to All Projects
                    return RedirectToAction("AllProjects");

                }
                catch (Exception)
                {
                    throw;
                }

            }

            return RedirectToAction("Create");

        }

        #endregion

        #region // GET: Projects/Edit/5
        // GET: Projects/Edit/5
        [Authorize(Roles = "Admin, ProjectManager")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null )
            {
                return NotFound();
            }

            int companyId = User.Identity.GetCompanyId().Value;

            // Add ViewModel instance
            AddProjectWithPMViewModel model = new();

            model.Project = await _projectService.GetProjectByIdAsync(id.Value, companyId);

            if (model.Project == null)
            {
                return NotFound();
            }

            // Load SelectLists with data, i.e. PMList & PriorityList
            model.PMList = new SelectList(await _rolesService.GetUsersInRoleAsync(Roles.ProjectManager.ToString(), companyId),
                         "Id", "FullName");
            model.PriorityList = new SelectList(await _lookupService.GetProjectPrioritiesAsync(), "Id", "Name");

            return View(model);
        }
        #endregion

        #region // POST: Projects/Edit/5
        // POST: Projects/Edit/5
        [Authorize(Roles = "Admin, ProjectManager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(AddProjectWithPMViewModel model)
        {

            // Check for Demo User
            if (await IsDemoUser())
            {
                return new RedirectResult("~/Identity/Account/AccessDenied");
            }

            if (model != null)
            {
                try
                {
                    if (model.Project.ImageFormFile != null)
                    {
                        model.Project.ImageFileData = await _fileService.ConvertFileToByteArrayAsync(model.Project.ImageFormFile);
                        model.Project.ImageFileName = model.Project.ImageFormFile.FileName;
                        model.Project.ImageContentType = model.Project.ImageFormFile.ContentType;
                    }

                    await _projectService.UpdateProjectAsync(model.Project);
                  
                    // Add PM if one was chosen
                    if (!string.IsNullOrEmpty(model.PmId))
                    {
                        await _projectService.AddProjectManagerAsync(model.PmId, model.Project.Id);
                    }
                   
                    return RedirectToAction(nameof(AllProjects));

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await ProjectExists(model.Project.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }

                }
               
            }

            return RedirectToAction("Edit");
        }

        #endregion

        #region // GET: Projects/Archive/5
        // GET: Projects/Archive/5
        [Authorize(Roles = "Admin, ProjectManager")]
        public async Task<IActionResult> Archive(int? id)
        {
            if (id == null  )
            {
                return NotFound();
            }

            int companyId = User.Identity.GetCompanyId().Value;

            Project project = await  _projectService.GetProjectByIdAsync( id.Value , companyId );

            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }
        #endregion

        #region // POST: Projects/Archive/5
        // POST: Projects/Archive/5
        [Authorize(Roles = "Admin, ProjectManager")]
        [HttpPost, ActionName("Archive")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ArchiveConfirmed(int id)
        {

            // Check for Demo User
            if (await IsDemoUser())
            {
                return new RedirectResult("~/Identity/Account/AccessDenied");
            }

            int companyId = User.Identity.GetCompanyId().Value;

            Project project = await _projectService.GetProjectByIdAsync(id, companyId);
           
            await _projectService.ArchiveProjectAsync(project);

            return RedirectToAction(nameof(AllProjects));
        }
        #endregion

        #region // GET: Projects/Restore/5
        // GET: Projects/Restore/5
        [Authorize(Roles = "Admin, ProjectManager")]
        public async Task<IActionResult> Restore(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            int companyId = User.Identity.GetCompanyId().Value;

Views/Projects/AllProjects.cshtml
@using TheBugTracker.Models.Enums
@using Microsoft.AspNetCore.Identity
@using TheBugTracker.Services.Interfaces
@model IEnumerable<TheBugTracker.Models.Project>

@inject UserManager<BTUser> UserManager
@inject IBTProjectService ProjectService

@{
    ViewData["Title"] = "All Project";
	BTUser btUser = await UserManager.GetUserAsync(User);
}

<div class="d-flex align-items-center">
		<a class="" asp-action="AllProjects" asp-controller="Projects" style="color: rgb(23, 123, 227); margin-right : 15px" >  
			<i class="fa fa-arrow-left fa-lg" aria-hidden="true"></i> 
		</a>
		<h4 class="mb-0">All Project</h4>
</div>

<div class="d-flex align-items-center" style="margin-bottom : 20px">
		<a class="" asp-action="Dashboard" asp-controller="Home" style="color: rgb(23, 123, 227); margin-right : 15px" >  
			<i class="fa fa-home fa-lg" aria-hidden="true"></i> </a>
		<p class="mb-0" style="margin-right : 5px">/ Projects</p>
		<p class="mb-0">/ All Project</p>
</div>


<!-- Column starts -->
<div class="col-xl-12">
  <div class="card dz-card" id="accordion-one">
    <div class="card-header flex-wrap">
      <div>
        <h4 class="card-title">All Projects</h4>
      </div>
    </div>
    <!--tab-content-->
    <div class="tab-content" id="myTabContent">
      <div
        class="tab-pane fade show active"
        id="Preview"
        role="tabpanel"
        aria-labelledby="home-tab"
      >
        <div class="card-body pt-0">
          <div class="table-responsive">
            <table id="example" class="display table" style="min-width: 845px">
              <thead>
                <tr>
                  <th>Project</th>
                  <th>End Date</th>
                  <th>Priority</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                                @foreach (var item in Model)
                                {
                    <tr>
                      <td>
                        <h6>@item.Name</h6>
                        <span>
                                          Created @item.StartDate.ToString( "dd MMM, yyyy"  ) 
                        </span>
                      </td>

                          <td> @item.EndDate.ToString( "dd MMM, yyyy"  )  
                      <td>
                                            @Html.DisplayFor(modelItem => item.ProjectPriority.Name)
                      </td>
                      <td>
                        <a
                          asp-action="Details"
                          asp-route-id="@item.Id"
                          class="btn btn-success shadow btn-xs sharp me-1"
                          ><i class="fa fa-eye"></i
                        ></a>

                                            @{
                                                bool isPM = (await
                                                                ProjectService.GetProjectManagerAsync(item.Id))?.Id ==
                                                                btUser.Id;
                                            } @if (User.IsInRole(nameof(Roles.Admin)) ||
                                                            isPM)
                                            {

                            <a
                              asp-action="Edit"
                              asp-route-id="@item.Id"
                              class="btn btn-primary shadow btn-xs sharp me-1"
                              ><i class="fa fa-pencil"></i
                            ></a>

                                                if (item.Archived)
                                                {
                                <a
                                  asp-action="Restore"
                                  asp-route-id="@item.Id"
                                  class="btn btn-info shadow btn-xs sharp"
                                  ><i class="fa fa-refresh"></i
                                ></a>
                                                }
                                                else
                                                {
                                <a
                                  asp-action="Archive"
                                  asp-route-id="@item.Id"
                                  class="btn btn-danger shadow btn-xs sharp"
                                  ><i class="fa fa-archive"></i
                                ></a>
                                                }
                                            }
                      </td>
                    </tr>
                                }
              </tbody>
            </table>
          </div>
        </div>
        <!-- /Default accordion -->
      </div>
      <div
        class="tab-pane fade"
        id="html"
        role="tabpanel"
        aria-labelledby="home-tab"
      >
        <div class="card-body pt-0 p-0 code-area"></div>
        <!-- /Default accordion -->
      </div>
    </div>
    <!--/tab-content-->
  </div>
</div>

<!-- Column ends -->

Views/Projects/Archive.cshtml
@model TheBugTracker.Models.Project

@{
    ViewData["Title"] = "Archive";
}



<div class="d-flex align-items-center">
    <a class="" asp-action="index" asp-controller="Projects" style="color: rgb(23, 123, 227); margin-right : 15px" >  <i class="fa fa-arrow-left fa-lg" aria-hidden="true"></i> </a>
    <h4 class="mb-0">Archive</h4>
</div>

<div class="d-flex align-items-center" style="margin-bottom : 20px">
    <a class="" asp-action="Dashboard" asp-controller="Home" style="color: rgb(23, 123, 227); margin-right : 15px" >  <i class="fa fa-home fa-lg" aria-hidden="true"></i> </a>
    <p class="mb-0" style="margin-right : 5px">/ Project</p>
    <p class="mb-0">/ Archive</p>
</div>


<h3>Are you sure you want to archive this project?</h3>


                    <div style = "margin-top : 20px" class="col-xl-12">
                        <div class="card dz-card" id="bootstrap-table5">
                            <div class="card-header flex-wrap d-flex justify-content-between  border-0">
                                <div>
                                    <h4 class="card-title">Projects</h4>
                                </div>
                            </div>
                               <!-- tab-content -->	
                            <div class="tab-content" id="myTabContent-4">
                                <div class="tab-pane fade show active" id="leftPosition" role="tabpanel" aria-labelledby="home-tab-4">
                                    <div class="card-body pt-0">
                                        <div class="table-responsive">
                                            <table class="table table-bordered table-responsive-sm">
                                                <!--  <thead>
                                                        <tr>
                                                            <th>#</th>
                                                            <th>Name</th>
                                                        </tr>

                                                      </thead>   --> 
                                                <tbody>
                                                    <tr>
                                                        <th> @Html.DisplayNameFor(model => model.Name) </th>
                                                        <td>  @Html.DisplayFor(model => model.Name) </td>
                                                    </tr>


                                                    <tr>
                                                        <th>@Html.DisplayNameFor(model => model.Description)</th>
                                                        <td> @Html.DisplayFor(model => model.Description) </td>
                                                    </tr>

                                                     <tr>
                                                        <th> @Html.DisplayNameFor(model => model.StartDate) </th>
                                                        <td>  @Model.StartDate.ToString( "dd MMM, yyyy" ) </td>
                                                    </tr>

                                                     <tr>
                                                        <th>  @Html.DisplayNameFor(model => model.EndDate) </th>
                                                        <td>  @Model.EndDate.ToString( "dd MMM, yyyy" ) </td>
                                                    </tr>


                                                     <tr>
                                                        <th>  @Html.DisplayNameFor(model => model.ProjectPriority.Name) </th>
                                                        <td>   @Html.DisplayFor(model => model.ProjectPriority.Name)  </td>
                                                    </tr>

                                                       

                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>

                                <div style = "margin: 20px" > 
                                        <form  asp-action="Archive">
                                            <input type="hidden" asp-for="Id" />
                                            <input type="submit" value="Archive" class="btn btn-danger" />  

                                     </form>
                               </div>

                            </div>





<!--  

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Archived)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Archived)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageFileName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageFileName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageFileData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageFileData)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageContentType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageContentType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectPriority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectPriority.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
-->

Views/Projects/ArchivedProject.cshtml
@using TheBugTracker.Models.Enums
@model IEnumerable<TheBugTracker.Models.Project>

@{
	ViewData["Title"] = "Archived Project";
}

<div class="d-flex align-items-center">
	<a class="" asp-action="AllProjects" asp-controller="Projects" style="color: rgb(23, 123, 227); margin-right : 15px" >  
        <i class="fa fa-arrow-left fa-lg" aria-hidden="true"></i> </a>
	<h4 class="mb-0">Archived Project</h4>
</div>

<div class="d-flex align-items-center" style="margin-bottom : 20px">
    <a class="" asp-action="Dashboard" asp-controller="Home" style="color: rgb(23, 123, 227); margin-right : 15px" >  <i class="fa fa-home fa-lg" aria-hidden="true"></i> </a>
    <p class="mb-0" style="margin-right : 5px">/ Projects</p>
	<p class="mb-0">/ ArchiveProject</p>
</div>

<!-- Column start -->
<div class="row">
<div class="col-xl-12">
  <div class="card dz-card" id="accordion-one">
    <div class="card-header flex-wrap">
      <div>
        <h4 class="card-title">Archived Project</h4>
      </div>
    </div>
    <!--tab-content-->
    <div class="tab-content" id="myTabContent">
      <div
        class="tab-pane fade show active"
        id="Preview"
        role="tabpanel"
        aria-labelledby="home-tab"
      >
        <div class="card-body pt-0">
          <div class="table-responsive">
            <table id="example" class="display table" style="min-width: 845px">
              <thead>
                <tr>
                  <th>Name</th>
             @*   <th>Description</th>  *@ 
                  <th>Start Date</th>
                  <th>End Date</th>
                  <th>Priority</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                @foreach (var item in Model)
                   {
                    <tr>
                      <td>@item.Name</td>
                                            @*  <td>@item.Description</td> *@ 
                      <td>@item.StartDate</td>
                          <td>  @Html.DisplayFor(modelItem => item.EndDate) </td>
                      <td>  @Html.DisplayFor(modelItem => item.ProjectPriority.Name) </td>
                      <td>
                        <a
                          asp-action="Details"
                          asp-route-id="@item.Id"
                          class="btn btn-success shadow btn-xs sharp me-1"
                          ><i class="fa fa-eye"></i
                        ></a>

                        <a
                          asp-action="Restore"
                          asp-route-id="@item.Id"
                          class="btn btn-info shadow btn-xs sharp"
                          ><i class="fa fa-refresh"></i
                        ></a>
                      </td>
                    </tr>
                                }
              </tbody>
            </table>
          </div>
        </div>
        <!-- /Default accordion -->
      </div>
      <div
        class="tab-pane fade"
        id="html"
        role="tabpanel"
        aria-labelledby="home-tab"
      >
        <div class="card-body pt-0 p-0 code-area"></div>
        <!-- /Default accordion -->
      </div>
    </div>
    <!--/tab-content-->
  </div>
</div>
</div>
<!-- Column ends -->

Views/Projects/AssignMembers.cshtml
@model TheBugTracker.Models.ViewModels.ProjectMembersViewModel

@{
    ViewData["Title"] = "Assign Members";
}


<div class="d-flex align-items-center">
        <a class="" asp-action="UnassignedProjects" asp-controller="Projects" style="color: rgb(23, 123, 227); margin-right : 15px" >  
            <i class="fa fa-arrow-left fa-lg" aria-hidden="true"></i> 
        </a>
        <h4 class="mb-0">Assign Members</h4>
</div>

<div class="d-flex align-items-center" style="margin-bottom : 20px">
        <a class="" asp-action="Dashboard" asp-controller="Home" style="color: rgb(23, 123, 227); margin-right : 15px" >  
            <i class="fa fa-home fa-lg" aria-hidden="true"></i> </a>
        <p class="mb-0" style="margin-right : 5px">/ Projects</p>
        <p class="mb-0">/ Assign Members</p>
</div>


<div class="">
    <div class="row">

        <div class="col-md-6">

            <div class="card shadow mt-4">

                <div class="card-body">
                    <form method="post" asp-action="AssignMembers" asp-controller="Projects">

                        <input hidden asp-for="Project.Id"/>

                        <h6></h6>
                        <p></p>

                        <div class="form-group">
                            <label style="margin-bottom : 10px" class="col-form-label"><strong>Assign Team Members</strong></label>
                            @*   <select required asp-for="@Model.SelectedUsers" class="form-control" asp-items="@Model.Users" multiple ></select> *@
                            <select required multiple class="default-select form-control wide mt-3"  asp-items="@Model.Users" asp-for="@Model.SelectedUsers" >
                            </select>
                        </div>

                       

                        <div class="form-group mt-3">
                            <input type="submit" value="Assign Users" class="btn btn-primary"/>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>

Views/Projects/AssignPM.cshtml
@model TheBugTracker.Models.ViewModels.AssignPMViewModel

@{
    ViewData["Title"] = "Assign PM";
}


<div class="d-flex align-items-center">
        <a class="" asp-action="UnassignedProjects" asp-controller="Projects" style="color: rgb(23, 123, 227); margin-right : 15px" >  
            <i class="fa fa-arrow-left fa-lg" aria-hidden="true"></i> 
        </a>
        <h4 class="mb-0">Assign Project Manager</h4>
</div>

<div class="d-flex align-items-center" style="margin-bottom : 20px">
        <a class="" asp-action="Dashboard" asp-controller="Home" style="color: rgb(23, 123, 227); margin-right : 15px" >  
            <i class="fa fa-home fa-lg" aria-hidden="true"></i> </a>
        <p class="mb-0" style="margin-right : 5px">/ Projects</p>
        <p class="mb-0">/ AssignPM</p>
</div>


<div class="">
    <div class="row">

        <div class="col-md-6">

            <div class="card shadow mt-4">

                <div class="card-body">
                    <form method="post" asp-action="AssignPM" asp-controller="Projects">
                        <input asp-for="Project.Id" hidden/>

                        <h6>@Model.Project.Name</h6>

                        <p>@Model.Project.Description</p>

                        <div class="form-group">
                            <label style="margin-bottom : 10px" class="col-form-label"><strong>Select Project Manager</strong></label>

                            <select asp-for="PMId" class="form-control" asp-items="@Model.PMList">
                                <option></option>
                            </select>
                        </div>
                        <div class="form-group mt-3">
                            <input type="submit" value="Assign" class="btn btn-primary"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>